### DISCUSSION TITLE
Use "original" deepstack API

### DISCUSSION THREAD

**Discussion by FabioDiS** [neilenns/node-deepstackai-trigger#404] [Q&A] [answered]
**What trouble are you having?**

Hi, my installation gone fine and it's working on my machine. I already looked for a possible solution but I can't get to work with the original deepstack. I would like to use it because of hw acceleration of my GPU. I tried to substitute the value of "deepstackUri" in `settings.json` with deepstack API exposed on "localhost:80" but the logs returns "Error: Failed to call DeepStack at http://localhost:80: Error: connect ECONNREFUSED 127.0.0.1:80". Do you have any suggestions? Thanks

**Log entries**

2020-12-08T18:42:45+01:00 [Trigger Person detector] /aiinput/ca1.2020-12-08_18-42-45_134.jpg: Analyzing
trigger_1       | 2020-12-08T18:42:45+01:00 [Trigger Person detector] Error: Failed to call DeepStack at http://localhost:80: Error: connect ECONNREFUSED 127.0.0.1:80
trigger_1       | 2020-12-08T18:42:45+01:00 [Trigger Person detector] /aiinput/ca1.2020-12-08_18-42-45_134.jpg: Analysis failed

**Installation details**

 - OS: Ubuntu 20.10

Edit:
my `docker-compose.yml`

```yaml
version: "3.8"
services:
  trigger:
    volumes:
      # Change d:/myfolder/myimages to point to the folder that will have the images
      # to analyze. Only change the local path that is before the :/aiinput portion.
      # Don't change the :/aiinput part. For example, if you are on Windows and your
      # images are stored locally in d:/blueiris/capturedImages your final line should
      # look like this:
      # d:/blueIris/capturedImages:/aiinput
      - /home/fabio/Downloads/Agent_Linux64_3_0_2_0/Media/WebServerRoot/Media/video/FXPCD/grabs:/aiinput

    environment:
      # Change this to match the timezone the images are produced in,
      # Typically this will be the timezone of the machine running
      # the Docker container. For a list of valid timezone values
      # see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones.
      # The value to use is in the "TZ database name" column.
      - TZ=Europe/Rome

    ports:
      # This port is used by the local web server when annotated images are enabled.
      # If you change the port used by the local web server in the settings.json file
      # this also has to change to match.
      - 4242:4242

    # ------------------------------------------------------------------------
    # Don't change anything below this line unless you know what you are doing
    secrets:
      - triggers
      - settings
    image: danecreekphotography/node-deepstackai-trigger:latest
    restart: always
    depends_on:
      - deepstack-ai

  deepstack-ai:
    image: deepquestai/deepstack:latest
    restart: always
    volumes:
      - localstorage:/datastore
    environment:
      - VISION-DETECTION=True

volumes:
  localstorage:

secrets:
  settings:
    # This should point to the location of the settings.json configuration file
    file: ./settings.json
  triggers:
    # This should point to the location of the triggers.json configuration file
    file: ./triggers.json
```

and my `settings.json`

```json
{
  // Leave this line alone. It enables Intellisense when editing this file in Visual Studio Code.
  "$schema": "https://raw.githubusercontent.com/danecreekphotography/node-deepstackai-trigger/main/src/schemas/settings.schema.json",

  // This is the default uri for Deepstack when deploying using the docker-compose.yaml file
  // provided in this sampleConfiguration folder. If you have another deployment of Deepstack
  // running elsewhere change this setting to point to the correction location.
  "deepstackUri": "http://deepstack-ai:5000/",

  // Set this to true to enable annotated images for use in trigger handlers.
  // There is a performance penalty to using this, leave it off unless
  // you really want to see the annotated images.
  "enableAnnotations": false,

  // Set this to true to enable the internal web server for remote access
  // to processed and annotated images.
  "enableWebServer": false,

  // Enables verbose logging. Useful when setting up the system to ensure
  // everything is running correctly.
  "verbose": true,

  // Set this to true if your images are stored in a remote folder that's
  // mounted as a network share and then mapped to the Docker image.
  "awaitWriteFinish": false,

  // Provides the configuration details for your MQTT server. To enable
  // mqtt set the uri, username (if required), password (if required),
  // and set enabled to true.
  "mqtt": {
    "uri": "mqtt://mqtt:1883",
    //"username": "user",
    //"password": "pass",
    "enabled": false
  },

  // Provides the configuration details for Telegram bot messages.
  // Set the botToken and enabled to true to use Telegram.
  "telegram": {
    "botToken": "1234567890:abcd",
    "enabled": true
  },

  // Provides the configuration details for Pushbullet notifications.
  // Set the accessToken and enabled to true to use Pushbullet.
  "pushbullet": {
    "accessToken": "access token here",
    "enabled": false
  },

  // Provides the configuration details for Pushover notifications.
  // Set the apiKey, userKey, and enabled to true to use Pushover.
  "pushover": {
    "apiKey": "api key here",
    "userKey": "user key here",
    "enabled": false
  }
}
```
